on: push

defaults:
  run:
    shell: bash
    
jobs:
  rando-title:
     runs-on: ubuntu-latest
     steps:
      - run: bash
      - run: sudo apt install hugo
      - run: echo 'Hugo has been installed!'
      - run: ls
      - run: echo 'Files have been compiled into a working site'
