on: push

defaults:
  run:
    shell: bash

jobs:
  rando-title:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps: 
      - uses: actions/checkout@v2
      - run: bash
      - run: sudo apt install hugo
      - run: echo 'Hugo has been installed!'
      - run: ls
      - run: hugo  
      - run: echo 'Files have been compiled into a working site'
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public/
      - uses: actions/deploy-pages@v4
